package com.example.demo.entity;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface LoginUserMapper {
	
    //select文。userテーブルから、usernameが一致しているものを検索
    @Select("select * from loginuser where username = #{username}")
    public LoginUser findByUsername(String username);//識別する
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginUser
     *
     * @mbggenerated Sun Jul 30 19:28:16 JST 2023
     */
    int countByExample(LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginUser
     *
     * @mbggenerated Sun Jul 30 19:28:16 JST 2023
     */
    int deleteByExample(LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginUser
     *
     * @mbggenerated Sun Jul 30 19:28:16 JST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginUser
     *
     * @mbggenerated Sun Jul 30 19:28:16 JST 2023
     */
    int insert(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginUser
     *
     * @mbggenerated Sun Jul 30 19:28:16 JST 2023
     */
    int insertSelective(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginUser
     *
     * @mbggenerated Sun Jul 30 19:28:16 JST 2023
     */
    List<LoginUser> selectByExample(LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginUser
     *
     * @mbggenerated Sun Jul 30 19:28:16 JST 2023
     */
    LoginUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginUser
     *
     * @mbggenerated Sun Jul 30 19:28:16 JST 2023
     */
    int updateByExampleSelective(@Param("record") LoginUser record, @Param("example") LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginUser
     *
     * @mbggenerated Sun Jul 30 19:28:16 JST 2023
     */
    int updateByExample(@Param("record") LoginUser record, @Param("example") LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginUser
     *
     * @mbggenerated Sun Jul 30 19:28:16 JST 2023
     */
    int updateByPrimaryKeySelective(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginUser
     *
     * @mbggenerated Sun Jul 30 19:28:16 JST 2023
     */
    int updateByPrimaryKey(LoginUser record);
}