package com.example.demo.entity;

import lombok.Data;

@Data
public class LoginUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginUser.id
     *
     * @mbggenerated Sun Jul 30 19:28:16 JST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginUser.username
     *
     * @mbggenerated Sun Jul 30 19:28:16 JST 2023
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginUser.password
     *
     * @mbggenerated Sun Jul 30 19:28:16 JST 2023
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginUser.id
     *
     * @return the value of LoginUser.id
     *
     * @mbggenerated Sun Jul 30 19:28:16 JST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginUser.id
     *
     * @param id the value for LoginUser.id
     *
     * @mbggenerated Sun Jul 30 19:28:16 JST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginUser.username
     *
     * @return the value of LoginUser.username
     *
     * @mbggenerated Sun Jul 30 19:28:16 JST 2023
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginUser.username
     *
     * @param username the value for LoginUser.username
     *
     * @mbggenerated Sun Jul 30 19:28:16 JST 2023
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginUser.password
     *
     * @return the value of LoginUser.password
     *
     * @mbggenerated Sun Jul 30 19:28:16 JST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginUser.password
     *
     * @param password the value for LoginUser.password
     *
     * @mbggenerated Sun Jul 30 19:28:16 JST 2023
     */
    public void setPassword(String password) {
        this.password = password;
    }
}